# Generated by Django 4.0.6 on 2023-12-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('danceability', models.DecimalField(decimal_places=10, max_digits=20)),
                ('energy', models.DecimalField(decimal_places=10, max_digits=20)),
                ('mode', models.IntegerField()),
                ('acousticness', models.DecimalField(decimal_places=10, max_digits=20)),
                ('tempo', models.DecimalField(decimal_places=10, max_digits=20)),
                ('duration_ms', models.IntegerField()),
                ('num_sections', models.IntegerField()),
                ('num_segments', models.IntegerField()),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('ratings_count', models.IntegerField(default=0)),
            ],
        ),
    ]
